micronaut:
  application:
    name: 'queryme'
  session:
    http:
      cookie: true
      header: true

datasources:
  default:
    url: jdbc:h2:tcp://localhost/~/devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
    show_sql: true

jpa:
  default:
    entity-scan:
      packages:
        - 'org.prieto.domain'
        - 'org.prieto.repository'
    properties:
      hibernate:
        show_sql: true
        bytecode:
          provider: none
        hbm2ddl:
          auto: update







